name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Load global cache (~/.esy/source)
        uses: actions/cache@v2
        with:
          path: ~/.esy/source
          key: source-${{ matrix.os }}-${{ hashFiles('**/index.json') }}

      - name: Install esy
        run: npm install -g esy@0.6.8

      - name: Install dependencies
        run: esy install

      - name: Print esy cache
        id: print_esy_cache
        run: node .github/workflows/print-esy-cache.js

      - name: Load dependencies cache
        id: deps-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.print_esy_cache.outputs.esy_cache }}
          key: build-${{ matrix.os }}-${{ hashFiles('**/index.json') }}
          restore-keys: build-${{ matrix.os }}-

      - name: Import dependencies
        run: esy import-build

      - name: Build dependencies
        run: esy build-dependencies

      - name: Build
        run: esy build

      - name: Run ppx Native tests
        run: esy test_native

      - name: Run ppx Native snapshot tests
        run: esy test_snapshot

      - name: Run runtests for Parser, vds & Lexer
        run: esy dune runtest --force

      - name: Export dependencies
        if: steps.deps-cache.outputs.cache-hit != 'true'
        run: esy export-dependencies

      - name: Upload artifacts for ${{ matrix.os }}
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.os }}
          path: _build/default/bin/ppx.exe

  e2e:
    needs: build
    name: BuckleScript tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Download artifacts
        uses: actions/download-artifact@master
        with:
          name: ${{ matrix.os }}
          path: _build/default/bin

      - name: Grant permission to run ppx
        run: chmod +x _build/default/bin/ppx.exe

      - name: Get cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
        working-directory: ./packages/ppx/test/bucklescript

      - name: Load global cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ matrix.os }}-${{ hashFiles('./packages/ppx/test/bucklescript/yarn.lock') }}
          restore-keys: yarn-${{ matrix.os }}-

      - name: Install dependencies
        run: yarn
        working-directory: ./packages/ppx/test/bucklescript

      - name: Build
        run: yarn build
        working-directory: ./packages/ppx/test/bucklescript

      - name: Test
        run: yarn test
        working-directory: ./packages/ppx/test/bucklescript

  publish:
    needs: build
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Make NPM release skeleton
        run: node scripts/release-make-skeleton.js

      - name: Download linux artifacts
        uses: actions/download-artifact@master
        with:
          name: ubuntu-latest
          path: _release/platform-linux-x64

      - name: Download macOS artifacts
        uses: actions/download-artifact@master
        with:
          name: macos-latest
          path: _release/platform-darwin-x64

      # - name: Download windows artifacts
      #   uses: actions/download-artifact@master
      #   with:
      #     name: windows-latest
      #     path: _release/platform-windows-x64

      - name: Create archives for Github release
        run: |
          cd _release/platform-darwin-x64
          zip -r ../../styled-ppx-darwin-x64.zip .
          cd ../..

          cd _release/platform-linux-x64
          zip -r ../../styled-ppx-linux-x64.zip .
          cd ../..

          # cd _release/platform-windows-x64
          # zip -r ../../styled-ppx-windows-x64.zip .
          # cd ../..

      - name: Create Github release
        id: create_release
        if: "startsWith(github.ref, 'refs/tags/v')"
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload styled-ppx-darwin-x64.zip to Github release
        if: "startsWith(github.ref, 'refs/tags/v')"
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: styled-ppx-darwin-x64.zip
          asset_name: styled-ppx-darwin-x64.zip
          asset_content_type: application/gzip

      - name: Upload styled-ppx-linux-x64.zip to Github release
        if: "startsWith(github.ref, 'refs/tags/v')"
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: styled-ppx-linux-x64.zip
          asset_name: styled-ppx-linux-x64.zip
          asset_content_type: application/gzip

      # - name: Upload styled-ppx-windows-x64.zip to Github release
      #   if: github.ref != 'refs/heads/master'
      #   uses: actions/upload-release-asset@v1.0.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: styled-ppx-windows-x64.zip
      #     asset_name: styled-ppx-windows-x64.zip
      #     asset_content_type: application/gzip

      - name: Print short SHA
        id: sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Release nightly NPM package
        if: github.event_name == 'pull_request'
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm config set scope "@davesnx"
          npm version prerelease --preid nightly.${{ steps.sha.outputs.sha_short }} -no-git-tag-version
          npm publish --access public --tag nightly
        working-directory: ./_release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Release NPM package
        if: "startsWith(github.ref, 'refs/tags/v')"
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm config set scope "@davesnx"
          npm publish --access public
        working-directory: ./_release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
